### PR TITLE
#160140608 Fix Schedule Timeline Strip Issue

### PR DESCRIPTION
**Pull request by muthash**
**What does this PR do?**
Fix schedule timeline strip issue

**Description of Task to be completed?**
The schedule timeline strip should show only from 8 am to 5 pm

**How should this be manually tested?**
- Run the application.
- Select a meeting room from a list of rooms.
- The timeline strip should display correctly from 8 am to 5 pm.

**Any background context you want to provide?**
Previously, The schedule timeline strip showed from 8 am to 9 pm and a user had to scroll sideways to see the end of the strip.

**What are the relevant pivotal tracker stories?**
#160140608

**Screenshots:**
_7" tablet_
screen shot 2018-09-05 at 11 50 21

_10" tablet_
screen shot 2018-09-07 at 09 47 33

### CODE REVIEW

**Comment by TheDancerCodes** [comment]
Hey @muthash 
I have run the app on a `10"` device and the schedule timeline view is still scrolling to 5PM.
Kindly look into this.
Event Schedule Timeline View

**Comment by TheDancerCodes** [comment]
Hi @muthash 
Kindly share screenshots for both 8" and 10" tablets on your PR before I merge this in.

**Comment by muthash** [comment]
The screenshots for both 7" and 10" tablets have been added.

**Comment by TheDancerCodes** [comment]
LGTM.
I am merging this in.
@muthash

**Pull request merged**
